Milestone 2: Create and remove from redux store
eroiyo/React-Bookstore pull request #2
Opened 2021-09-01 17:09 UTC by eroiyo

Hello Microverse Community, this is the milestone where we add to create and remove functions, some of this was already implemented in the first milestone, but they have been implemented with useSelector and useDispatch

*Created Redux store
*Used SelectQuerys
*Used UseDispatch

2021-09-01 18:23 UTC, vichuge requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your PR messages are descriptive ✔️

## Aspects to improve ♻️

- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-01 18:23 UTC, vichuge commented on src/redux/cofigureStore.js
> +export default store;
- [ ] About configure the store, it's important to add combineReducers to use more than only one, at this moment you have a reducer, but you can't add more if is necessary. Please add it to the project 🍰 
- [ ] At the same time, please, add applyMiddleware. This is important to the project structure too. 🐻

2021-09-01 18:23 UTC, vichuge commented on src/redux/books/Book.js
> +const initState = { books: [] };
- [ ] Please, the initialState should be an empty array, in this moment you have an object. I kindly invite you to change it. 🐱

2021-09-01 18:23 UTC, vichuge commented on src/components/Books/Form.js
>      const bookGenre = document.getElementById('book-genre').value;
- [ ] Please, for the book info you could add hooks, something like `const [name, setName] = useState('');` and then pass the state values to include on the form when you submit a new book. 🐻

2021-09-01 18:23 UTC, vichuge commented on src/components/Books/Form.js
>        <input placeholder="author" type="text" id="book-author" />
- [ ] To each input, you could add the onChange() function to take the value for the input, and add it to the local state, this will help to have your project more according to redux tools.

2021-09-01 18:23 UTC, vichuge commented on src/components/Books/Form.js
> -    pushBook(newBook);
- [ ] When you push the bok, try to use the local state values (hooks) in place to use local variables. According to the redux tool. 🐵

2021-09-01 18:23 UTC, vichuge commented on src/components/Books/Book.js
> +      <button type="button" onClick={() => dispatch(deleteBook(id))}>delete</button>
- [ ] At this point is a good idea to dispatch directly to the onClick function on the button, but when you add the API functionality you could struggle with this a little bit. Please, in place to dispatch directly, create a function where you can dispatch and add more functionality in the future on this part. 🌷 
- Hint: Before the render (return), type this function to add more functionality in the future. This should be made in the component.

2021-09-01 23:02 UTC, mricanho requested changes
Hi @eroiyo, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [ ] Remember that all the linters must pass in order to approve your project, please fix the linters issues.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-02 06:51 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashbaord. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-09-02 06:57 UTC, eroiyo commented
Thanks everyone!

2021-09-02 06:57 UTC, merged